package com.github.dantezitello.weatherapp.common.administration;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;

public enum Country {
    //This file was generated using excel and data from the ISO website

    @JsonProperty("Afghanistan")                        @JsonAlias({"AF","AFG"}) AFGHANISTAN("Afghanistan","AF","AFG"),
    @JsonProperty("Albania")                            @JsonAlias({"AL","ALB"}) ALBANIA("Albania","AL","ALB"),
    @JsonProperty("Algeria")                            @JsonAlias({"DZ","DZA"}) ALGERIA("Algeria","DZ","DZA"),
    @JsonProperty("American Samoa")                     @JsonAlias({"AS","ASM"}) AMERICAN_SAMOA("American Samoa","AS","ASM"),
    @JsonProperty("Andorra")                            @JsonAlias({"AD","AND"}) ANDORRA("Andorra","AD","AND"),
    @JsonProperty("Angola")                             @JsonAlias({"AO","AGO"}) ANGOLA("Angola","AO","AGO"),
    @JsonProperty("Anguilla")                           @JsonAlias({"AI","AIA"}) ANGUILLA("Anguilla","AI","AIA"),
    @JsonProperty("Antarctica")                         @JsonAlias({"AQ","ATA"}) ANTARCTICA("Antarctica","AQ","ATA"),
    @JsonProperty("Antigua and Barbuda")                @JsonAlias({"AG","ATG"}) ANTIGUA_AND_BARBUDA("Antigua and Barbuda","AG","ATG"),
    @JsonProperty("Argentina")                          @JsonAlias({"AR","ARG"}) ARGENTINA("Argentina","AR","ARG"),
    @JsonProperty("Armenia")                            @JsonAlias({"AM","ARM"}) ARMENIA("Armenia","AM","ARM"),
    @JsonProperty("Aruba")                              @JsonAlias({"AW","ABW"}) ARUBA("Aruba","AW","ABW"),
    @JsonProperty("Australia")                          @JsonAlias({"AU","AUS"}) AUSTRALIA("Australia","AU","AUS"),
    @JsonProperty("Austria")                            @JsonAlias({"AT","AUT"}) AUSTRIA("Austria","AT","AUT"),
    @JsonProperty("Azerbaijan")                         @JsonAlias({"AZ","AZE"}) AZERBAIJAN("Azerbaijan","AZ","AZE"),
    @JsonProperty("Bahamas")                            @JsonAlias({"BS","BHS"}) BAHAMAS("Bahamas","BS","BHS"),
    @JsonProperty("Bahrain")                            @JsonAlias({"BH","BHR"}) BAHRAIN("Bahrain","BH","BHR"),
    @JsonProperty("Bangladesh")                         @JsonAlias({"BD","BGD"}) BANGLADESH("Bangladesh","BD","BGD"),
    @JsonProperty("Barbados")                           @JsonAlias({"BB","BRB"}) BARBADOS("Barbados","BB","BRB"),
    @JsonProperty("Belarus")                            @JsonAlias({"BY","BLR"}) BELARUS("Belarus","BY","BLR"),
    @JsonProperty("Belgium")                            @JsonAlias({"BE","BEL"}) BELGIUM("Belgium","BE","BEL"),
    @JsonProperty("Belize")                             @JsonAlias({"BZ","BLZ"}) BELIZE("Belize","BZ","BLZ"),
    @JsonProperty("Benin")                              @JsonAlias({"BJ","BEN"}) BENIN("Benin","BJ","BEN"),
    @JsonProperty("Bermuda")                            @JsonAlias({"BM","BMU"}) BERMUDA("Bermuda","BM","BMU"),
    @JsonProperty("Bhutan")                             @JsonAlias({"BT","BTN"}) BHUTAN("Bhutan","BT","BTN"),
    @JsonProperty("Bolivia")                            @JsonAlias({"BO","BOL"}) BOLIVIA("Bolivia","BO","BOL"),
    @JsonProperty("Bosnia and Herzegovina")             @JsonAlias({"BA","BIH"}) BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina","BA","BIH"),
    @JsonProperty("Botswana")                           @JsonAlias({"BW","BWA"}) BOTSWANA("Botswana","BW","BWA"),
    @JsonProperty("Brazil")                             @JsonAlias({"BR","BRA"}) BRAZIL("Brazil","BR","BRA"),
    @JsonProperty("British Indian Ocean Territory")     @JsonAlias({"IO","IOT"}) BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory","IO","IOT"),
    @JsonProperty("British Virgin Islands")             @JsonAlias({"VG","VGB"}) BRITISH_VIRGIN_ISLANDS("British Virgin Islands","VG","VGB"),
    @JsonProperty("Brunei")                             @JsonAlias({"BN","BRN"}) BRUNEI("Brunei","BN","BRN"),
    @JsonProperty("Bulgaria")                           @JsonAlias({"BG","BGR"}) BULGARIA("Bulgaria","BG","BGR"),
    @JsonProperty("Burkina Faso")                       @JsonAlias({"BF","BFA"}) BURKINA_FASO("Burkina Faso","BF","BFA"),
    @JsonProperty("Burundi")                            @JsonAlias({"BI","BDI"}) BURUNDI("Burundi","BI","BDI"),
    @JsonProperty("Cambodia")                           @JsonAlias({"KH","KHM"}) CAMBODIA("Cambodia","KH","KHM"),
    @JsonProperty("Cameroon")                           @JsonAlias({"CM","CMR"}) CAMEROON("Cameroon","CM","CMR"),
    @JsonProperty("Canada")                             @JsonAlias({"CA","CAN"}) CANADA("Canada","CA","CAN"),
    @JsonProperty("Cape Verde")                         @JsonAlias({"CV","CPV"}) CAPE_VERDE("Cape Verde","CV","CPV"),
    @JsonProperty("Cayman Islands")                     @JsonAlias({"KY","CYM"}) CAYMAN_ISLANDS("Cayman Islands","KY","CYM"),
    @JsonProperty("Central African Republic")           @JsonAlias({"CF","CAF"}) CENTRAL_AFRICAN_REPUBLIC("Central African Republic","CF","CAF"),
    @JsonProperty("Chad")                               @JsonAlias({"TD","TCD"}) CHAD("Chad","TD","TCD"),
    @JsonProperty("Chile")                              @JsonAlias({"CL","CHL"}) CHILE("Chile","CL","CHL"),
    @JsonProperty("China")                              @JsonAlias({"CN","CHN"}) CHINA("China","CN","CHN"),
    @JsonProperty("Christmas Island")                   @JsonAlias({"CX","CXR"}) CHRISTMAS_ISLAND("Christmas Island","CX","CXR"),
    @JsonProperty("Cocos Islands")                      @JsonAlias({"CC","CCK"}) COCOS_ISLANDS("Cocos Islands","CC","CCK"),
    @JsonProperty("Colombia")                           @JsonAlias({"CO","COL"}) COLOMBIA("Colombia","CO","COL"),
    @JsonProperty("Comoros")                            @JsonAlias({"KM","COM"}) COMOROS("Comoros","KM","COM"),
    @JsonProperty("Cook Islands")                       @JsonAlias({"CK","COK"}) COOK_ISLANDS("Cook Islands","CK","COK"),
    @JsonProperty("Costa Rica")                         @JsonAlias({"CR","CRI"}) COSTA_RICA("Costa Rica","CR","CRI"),
    @JsonProperty("Croatia")                            @JsonAlias({"HR","HRV"}) CROATIA("Croatia","HR","HRV"),
    @JsonProperty("Cuba")                               @JsonAlias({"CU","CUB"}) CUBA("Cuba","CU","CUB"),
    @JsonProperty("Curacao")                            @JsonAlias({"CW","CUW"}) CURACAO("Curacao","CW","CUW"),
    @JsonProperty("Cyprus")                             @JsonAlias({"CY","CYP"}) CYPRUS("Cyprus","CY","CYP"),
    @JsonProperty("Czech Republic")                     @JsonAlias({"CZ","CZE"}) CZECH_REPUBLIC("Czech Republic","CZ","CZE"),
    @JsonProperty("Democratic Republic of the Congo")   @JsonAlias({"CD","COD"}) DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Democratic Republic of the Congo","CD","COD"),
    @JsonProperty("Denmark")                            @JsonAlias({"DK","DNK"}) DENMARK("Denmark","DK","DNK"),
    @JsonProperty("Djibouti")                           @JsonAlias({"DJ","DJI"}) DJIBOUTI("Djibouti","DJ","DJI"),
    @JsonProperty("Dominica")                           @JsonAlias({"DM","DMA"}) DOMINICA("Dominica","DM","DMA"),
    @JsonProperty("Dominican Republic")                 @JsonAlias({"DO","DOM"}) DOMINICAN_REPUBLIC("Dominican Republic","DO","DOM"),
    @JsonProperty("East Timor")                         @JsonAlias({"TL","TLS"}) EAST_TIMOR("East Timor","TL","TLS"),
    @JsonProperty("Ecuador")                            @JsonAlias({"EC","ECU"}) ECUADOR("Ecuador","EC","ECU"),
    @JsonProperty("Egypt")                              @JsonAlias({"EG","EGY"}) EGYPT("Egypt","EG","EGY"),
    @JsonProperty("El Salvador")                        @JsonAlias({"SV","SLV"}) EL_SALVADOR("El Salvador","SV","SLV"),
    @JsonProperty("Equatorial Guinea")                  @JsonAlias({"GQ","GNQ"}) EQUATORIAL_GUINEA("Equatorial Guinea","GQ","GNQ"),
    @JsonProperty("Eritrea")                            @JsonAlias({"ER","ERI"}) ERITREA("Eritrea","ER","ERI"),
    @JsonProperty("Estonia")                            @JsonAlias({"EE","EST"}) ESTONIA("Estonia","EE","EST"),
    @JsonProperty("Ethiopia")                           @JsonAlias({"ET","ETH"}) ETHIOPIA("Ethiopia","ET","ETH"),
    @JsonProperty("Falkland Islands")                   @JsonAlias({"FK","FLK"}) FALKLAND_ISLANDS("Falkland Islands","FK","FLK"),
    @JsonProperty("Faroe Islands")                      @JsonAlias({"FO","FRO"}) FAROE_ISLANDS("Faroe Islands","FO","FRO"),
    @JsonProperty("Fiji")                               @JsonAlias({"FJ","FJI"}) FIJI("Fiji","FJ","FJI"),
    @JsonProperty("Finland")                            @JsonAlias({"FI","FIN"}) FINLAND("Finland","FI","FIN"),
    @JsonProperty("France")                             @JsonAlias({"FR","FRA"}) FRANCE("France","FR","FRA"),
    @JsonProperty("French Polynesia")                   @JsonAlias({"PF","PYF"}) FRENCH_POLYNESIA("French Polynesia","PF","PYF"),
    @JsonProperty("Gabon")                              @JsonAlias({"GA","GAB"}) GABON("Gabon","GA","GAB"),
    @JsonProperty("Gambia")                             @JsonAlias({"GM","GMB"}) GAMBIA("Gambia","GM","GMB"),
    @JsonProperty("Georgia")                            @JsonAlias({"GE","GEO"}) GEORGIA("Georgia","GE","GEO"),
    @JsonProperty("Germany")                            @JsonAlias({"DE","DEU"}) GERMANY("Germany","DE","DEU"),
    @JsonProperty("Ghana")                              @JsonAlias({"GH","GHA"}) GHANA("Ghana","GH","GHA"),
    @JsonProperty("Gibraltar")                          @JsonAlias({"GI","GIB"}) GIBRALTAR("Gibraltar","GI","GIB"),
    @JsonProperty("Greece")                             @JsonAlias({"GR","GRC"}) GREECE("Greece","GR","GRC"),
    @JsonProperty("Greenland")                          @JsonAlias({"GL","GRL"}) GREENLAND("Greenland","GL","GRL"),
    @JsonProperty("Grenada")                            @JsonAlias({"GD","GRD"}) GRENADA("Grenada","GD","GRD"),
    @JsonProperty("Guam")                               @JsonAlias({"GU","GUM"}) GUAM("Guam","GU","GUM"),
    @JsonProperty("Guatemala")                          @JsonAlias({"GT","GTM"}) GUATEMALA("Guatemala","GT","GTM"),
    @JsonProperty("Guernsey")                           @JsonAlias({"GG","GGY"}) GUERNSEY("Guernsey","GG","GGY"),
    @JsonProperty("Guinea")                             @JsonAlias({"GN","GIN"}) GUINEA("Guinea","GN","GIN"),
    @JsonProperty("Guinea-Bissau")                      @JsonAlias({"GW","GNB"}) GUINEA_BISSAU("Guinea-Bissau","GW","GNB"),
    @JsonProperty("Guyana")                             @JsonAlias({"GY","GUY"}) GUYANA("Guyana","GY","GUY"),
    @JsonProperty("Haiti")                              @JsonAlias({"HT","HTI"}) HAITI("Haiti","HT","HTI"),
    @JsonProperty("Honduras")                           @JsonAlias({"HN","HND"}) HONDURAS("Honduras","HN","HND"),
    @JsonProperty("Hong Kong")                          @JsonAlias({"HK","HKG"}) HONG_KONG("Hong Kong","HK","HKG"),
    @JsonProperty("Hungary")                            @JsonAlias({"HU","HUN"}) HUNGARY("Hungary","HU","HUN"),
    @JsonProperty("Iceland")                            @JsonAlias({"IS","ISL"}) ICELAND("Iceland","IS","ISL"),
    @JsonProperty("India")                              @JsonAlias({"IN","IND"}) INDIA("India","IN","IND"),
    @JsonProperty("Indonesia")                          @JsonAlias({"ID","IDN"}) INDONESIA("Indonesia","ID","IDN"),
    @JsonProperty("Iran")                               @JsonAlias({"IR","IRN"}) IRAN("Iran","IR","IRN"),
    @JsonProperty("Iraq")                               @JsonAlias({"IQ","IRQ"}) IRAQ("Iraq","IQ","IRQ"),
    @JsonProperty("Ireland")                            @JsonAlias({"IE","IRL"}) IRELAND("Ireland","IE","IRL"),
    @JsonProperty("Isle of Man")                        @JsonAlias({"IM","IMN"}) ISLE_OF_MAN("Isle of Man","IM","IMN"),
    @JsonProperty("Israel")                             @JsonAlias({"IL","ISR"}) ISRAEL("Israel","IL","ISR"),
    @JsonProperty("Italy")                              @JsonAlias({"IT","ITA"}) ITALY("Italy","IT","ITA"),
    @JsonProperty("Ivory Coast")                        @JsonAlias({"CI","CIV"}) IVORY_COAST("Ivory Coast","CI","CIV"),
    @JsonProperty("Jamaica")                            @JsonAlias({"JM","JAM"}) JAMAICA("Jamaica","JM","JAM"),
    @JsonProperty("Japan")                              @JsonAlias({"JP","JPN"}) JAPAN("Japan","JP","JPN"),
    @JsonProperty("Jersey")                             @JsonAlias({"JE","JEY"}) JERSEY("Jersey","JE","JEY"),
    @JsonProperty("Jordan")                             @JsonAlias({"JO","JOR"}) JORDAN("Jordan","JO","JOR"),
    @JsonProperty("Kazakhstan")                         @JsonAlias({"KZ","KAZ"}) KAZAKHSTAN("Kazakhstan","KZ","KAZ"),
    @JsonProperty("Kenya")                              @JsonAlias({"KE","KEN"}) KENYA("Kenya","KE","KEN"),
    @JsonProperty("Kiribati")                           @JsonAlias({"KI","KIR"}) KIRIBATI("Kiribati","KI","KIR"),
    @JsonProperty("Kosovo")                             @JsonAlias({"XK","XKX"}) KOSOVO("Kosovo","XK","XKX"),
    @JsonProperty("Kuwait")                             @JsonAlias({"KW","KWT"}) KUWAIT("Kuwait","KW","KWT"),
    @JsonProperty("Kyrgyzstan")                         @JsonAlias({"KG","KGZ"}) KYRGYZSTAN("Kyrgyzstan","KG","KGZ"),
    @JsonProperty("Laos")                               @JsonAlias({"LA","LAO"}) LAOS("Laos","LA","LAO"),
    @JsonProperty("Latvia")                             @JsonAlias({"LV","LVA"}) LATVIA("Latvia","LV","LVA"),
    @JsonProperty("Lebanon")                            @JsonAlias({"LB","LBN"}) LEBANON("Lebanon","LB","LBN"),
    @JsonProperty("Lesotho")                            @JsonAlias({"LS","LSO"}) LESOTHO("Lesotho","LS","LSO"),
    @JsonProperty("Liberia")                            @JsonAlias({"LR","LBR"}) LIBERIA("Liberia","LR","LBR"),
    @JsonProperty("Libya")                              @JsonAlias({"LY","LBY"}) LIBYA("Libya","LY","LBY"),
    @JsonProperty("Liechtenstein")                      @JsonAlias({"LI","LIE"}) LIECHTENSTEIN("Liechtenstein","LI","LIE"),
    @JsonProperty("Lithuania")                          @JsonAlias({"LT","LTU"}) LITHUANIA("Lithuania","LT","LTU"),
    @JsonProperty("Luxembourg")                         @JsonAlias({"LU","LUX"}) LUXEMBOURG("Luxembourg","LU","LUX"),
    @JsonProperty("Macau")                              @JsonAlias({"MO","MAC"}) MACAU("Macau","MO","MAC"),
    @JsonProperty("Macedonia")                          @JsonAlias({"MK","MKD"}) MACEDONIA("Macedonia","MK","MKD"),
    @JsonProperty("Madagascar")                         @JsonAlias({"MG","MDG"}) MADAGASCAR("Madagascar","MG","MDG"),
    @JsonProperty("Malawi")                             @JsonAlias({"MW","MWI"}) MALAWI("Malawi","MW","MWI"),
    @JsonProperty("Malaysia")                           @JsonAlias({"MY","MYS"}) MALAYSIA("Malaysia","MY","MYS"),
    @JsonProperty("Maldives")                           @JsonAlias({"MV","MDV"}) MALDIVES("Maldives","MV","MDV"),
    @JsonProperty("Mali")                               @JsonAlias({"ML","MLI"}) MALI("Mali","ML","MLI"),
    @JsonProperty("Malta")                              @JsonAlias({"MT","MLT"}) MALTA("Malta","MT","MLT"),
    @JsonProperty("Marshall Islands")                   @JsonAlias({"MH","MHL"}) MARSHALL_ISLANDS("Marshall Islands","MH","MHL"),
    @JsonProperty("Mauritania")                         @JsonAlias({"MR","MRT"}) MAURITANIA("Mauritania","MR","MRT"),
    @JsonProperty("Mauritius")                          @JsonAlias({"MU","MUS"}) MAURITIUS("Mauritius","MU","MUS"),
    @JsonProperty("Mayotte")                            @JsonAlias({"YT","MYT"}) MAYOTTE("Mayotte","YT","MYT"),
    @JsonProperty("Mexico")                             @JsonAlias({"MX","MEX"}) MEXICO("Mexico","MX","MEX"),
    @JsonProperty("Micronesia")                         @JsonAlias({"FM","FSM"}) MICRONESIA("Micronesia","FM","FSM"),
    @JsonProperty("Moldova")                            @JsonAlias({"MD","MDA"}) MOLDOVA("Moldova","MD","MDA"),
    @JsonProperty("Monaco")                             @JsonAlias({"MC","MCO"}) MONACO("Monaco","MC","MCO"),
    @JsonProperty("Mongolia")                           @JsonAlias({"MN","MNG"}) MONGOLIA("Mongolia","MN","MNG"),
    @JsonProperty("Montenegro")                         @JsonAlias({"ME","MNE"}) MONTENEGRO("Montenegro","ME","MNE"),
    @JsonProperty("Montserrat")                         @JsonAlias({"MS","MSR"}) MONTSERRAT("Montserrat","MS","MSR"),
    @JsonProperty("Morocco")                            @JsonAlias({"MA","MAR"}) MOROCCO("Morocco","MA","MAR"),
    @JsonProperty("Mozambique")                         @JsonAlias({"MZ","MOZ"}) MOZAMBIQUE("Mozambique","MZ","MOZ"),
    @JsonProperty("Myanmar")                            @JsonAlias({"MM","MMR"}) MYANMAR("Myanmar","MM","MMR"),
    @JsonProperty("Namibia")                            @JsonAlias({"NA","NAM"}) NAMIBIA("Namibia","NA","NAM"),
    @JsonProperty("Nauru")                              @JsonAlias({"NR","NRU"}) NAURU("Nauru","NR","NRU"),
    @JsonProperty("Nepal")                              @JsonAlias({"NP","NPL"}) NEPAL("Nepal","NP","NPL"),
    @JsonProperty("Netherlands")                        @JsonAlias({"NL","NLD"}) NETHERLANDS("Netherlands","NL","NLD"),
    @JsonProperty("Netherlands Antilles")               @JsonAlias({"AN","ANT"}) NETHERLANDS_ANTILLES("Netherlands Antilles","AN","ANT"),
    @JsonProperty("New Caledonia")                      @JsonAlias({"NC","NCL"}) NEW_CALEDONIA("New Caledonia","NC","NCL"),
    @JsonProperty("New Zealand")                        @JsonAlias({"NZ","NZL"}) NEW_ZEALAND("New Zealand","NZ","NZL"),
    @JsonProperty("Nicaragua")                          @JsonAlias({"NI","NIC"}) NICARAGUA("Nicaragua","NI","NIC"),
    @JsonProperty("Niger")                              @JsonAlias({"NE","NER"}) NIGER("Niger","NE","NER"),
    @JsonProperty("Nigeria")                            @JsonAlias({"NG","NGA"}) NIGERIA("Nigeria","NG","NGA"),
    @JsonProperty("Niue")                               @JsonAlias({"NU","NIU"}) NIUE("Niue","NU","NIU"),
    @JsonProperty("North Korea")                        @JsonAlias({"KP","PRK"}) NORTH_KOREA("North Korea","KP","PRK"),
    @JsonProperty("Northern Mariana Islands")           @JsonAlias({"MP","MNP"}) NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands","MP","MNP"),
    @JsonProperty("Norway")                             @JsonAlias({"NO","NOR"}) NORWAY("Norway","NO","NOR"),
    @JsonProperty("Oman")                               @JsonAlias({"OM","OMN"}) OMAN("Oman","OM","OMN"),
    @JsonProperty("Pakistan")                           @JsonAlias({"PK","PAK"}) PAKISTAN("Pakistan","PK","PAK"),
    @JsonProperty("Palau")                              @JsonAlias({"PW","PLW"}) PALAU("Palau","PW","PLW"),
    @JsonProperty("Palestine")                          @JsonAlias({"PS","PSE"}) PALESTINE("Palestine","PS","PSE"),
    @JsonProperty("Panama")                             @JsonAlias({"PA","PAN"}) PANAMA("Panama","PA","PAN"),
    @JsonProperty("Papua New Guinea")                   @JsonAlias({"PG","PNG"}) PAPUA_NEW_GUINEA("Papua New Guinea","PG","PNG"),
    @JsonProperty("Paraguay")                           @JsonAlias({"PY","PRY"}) PARAGUAY("Paraguay","PY","PRY"),
    @JsonProperty("Peru")                               @JsonAlias({"PE","PER"}) PERU("Peru","PE","PER"),
    @JsonProperty("Philippines")                        @JsonAlias({"PH","PHL"}) PHILIPPINES("Philippines","PH","PHL"),
    @JsonProperty("Pitcairn")                           @JsonAlias({"PN","PCN"}) PITCAIRN("Pitcairn","PN","PCN"),
    @JsonProperty("Poland")                             @JsonAlias({"PL","POL"}) POLAND("Poland","PL","POL"),
    @JsonProperty("Portugal")                           @JsonAlias({"PT","PRT"}) PORTUGAL("Portugal","PT","PRT"),
    @JsonProperty("Puerto Rico")                        @JsonAlias({"PR","PRI"}) PUERTO_RICO("Puerto Rico","PR","PRI"),
    @JsonProperty("Qatar")                              @JsonAlias({"QA","QAT"}) QATAR("Qatar","QA","QAT"),
    @JsonProperty("Republic of the Congo")              @JsonAlias({"CG","COG"}) REPUBLIC_OF_THE_CONGO("Republic of the Congo","CG","COG"),
    @JsonProperty("Reunion")                            @JsonAlias({"RE","REU"}) REUNION("Reunion","RE","REU"),
    @JsonProperty("Romania")                            @JsonAlias({"RO","ROU"}) ROMANIA("Romania","RO","ROU"),
    @JsonProperty("Russia")                             @JsonAlias({"RU","RUS"}) RUSSIA("Russia","RU","RUS"),
    @JsonProperty("Rwanda")                             @JsonAlias({"RW","RWA"}) RWANDA("Rwanda","RW","RWA"),
    @JsonProperty("Saint Barthelemy")                   @JsonAlias({"BL","BLM"}) SAINT_BARTHELEMY("Saint Barthelemy","BL","BLM"),
    @JsonProperty("Saint Helena")                       @JsonAlias({"SH","SHN"}) SAINT_HELENA("Saint Helena","SH","SHN"),
    @JsonProperty("Saint Kitts and Nevis")              @JsonAlias({"KN","KNA"}) SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis","KN","KNA"),
    @JsonProperty("Saint Lucia")                        @JsonAlias({"LC","LCA"}) SAINT_LUCIA("Saint Lucia","LC","LCA"),
    @JsonProperty("Saint Martin")                       @JsonAlias({"MF","MAF"}) SAINT_MARTIN("Saint Martin","MF","MAF"),
    @JsonProperty("Saint Pierre and Miquelon")          @JsonAlias({"PM","SPM"}) SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon","PM","SPM"),
    @JsonProperty("Saint Vincent and the Grenadines")   @JsonAlias({"VC","VCT"}) SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines","VC","VCT"),
    @JsonProperty("Samoa")                              @JsonAlias({"WS","WSM"}) SAMOA("Samoa","WS","WSM"),
    @JsonProperty("San Marino")                         @JsonAlias({"SM","SMR"}) SAN_MARINO("San Marino","SM","SMR"),
    @JsonProperty("Sao Tome and Principe")              @JsonAlias({"ST","STP"}) SAO_TOME_AND_PRINCIPE("Sao Tome and Principe","ST","STP"),
    @JsonProperty("Saudi Arabia")                       @JsonAlias({"SA","SAU"}) SAUDI_ARABIA("Saudi Arabia","SA","SAU"),
    @JsonProperty("Senegal")                            @JsonAlias({"SN","SEN"}) SENEGAL("Senegal","SN","SEN"),
    @JsonProperty("Serbia")                             @JsonAlias({"RS","SRB"}) SERBIA("Serbia","RS","SRB"),
    @JsonProperty("Seychelles")                         @JsonAlias({"SC","SYC"}) SEYCHELLES("Seychelles","SC","SYC"),
    @JsonProperty("Sierra Leone")                       @JsonAlias({"SL","SLE"}) SIERRA_LEONE("Sierra Leone","SL","SLE"),
    @JsonProperty("Singapore")                          @JsonAlias({"SG","SGP"}) SINGAPORE("Singapore","SG","SGP"),
    @JsonProperty("Sint Maarten")                       @JsonAlias({"SX","SXM"}) SINT_MAARTEN("Sint Maarten","SX","SXM"),
    @JsonProperty("Slovakia")                           @JsonAlias({"SK","SVK"}) SLOVAKIA("Slovakia","SK","SVK"),
    @JsonProperty("Slovenia")                           @JsonAlias({"SI","SVN"}) SLOVENIA("Slovenia","SI","SVN"),
    @JsonProperty("Solomon Islands")                    @JsonAlias({"SB","SLB"}) SOLOMON_ISLANDS("Solomon Islands","SB","SLB"),
    @JsonProperty("Somalia")                            @JsonAlias({"SO","SOM"}) SOMALIA("Somalia","SO","SOM"),
    @JsonProperty("South Africa")                       @JsonAlias({"ZA","ZAF"}) SOUTH_AFRICA("South Africa","ZA","ZAF"),
    @JsonProperty("South Korea")                        @JsonAlias({"KR","KOR"}) SOUTH_KOREA("South Korea","KR","KOR"),
    @JsonProperty("South Sudan")                        @JsonAlias({"SS","SSD"}) SOUTH_SUDAN("South Sudan","SS","SSD"),
    @JsonProperty("Spain")                              @JsonAlias({"ES","ESP"}) SPAIN("Spain","ES","ESP"),
    @JsonProperty("Sri Lanka")                          @JsonAlias({"LK","LKA"}) SRI_LANKA("Sri Lanka","LK","LKA"),
    @JsonProperty("Sudan")                              @JsonAlias({"SD","SDN"}) SUDAN("Sudan","SD","SDN"),
    @JsonProperty("Suriname")                           @JsonAlias({"SR","SUR"}) SURINAME("Suriname","SR","SUR"),
    @JsonProperty("Svalbard and Jan Mayen")             @JsonAlias({"SJ","SJM"}) SVALBARD_AND_JAN_MAYEN("Svalbard and Jan Mayen","SJ","SJM"),
    @JsonProperty("Swaziland")                          @JsonAlias({"SZ","SWZ"}) SWAZILAND("Swaziland","SZ","SWZ"),
    @JsonProperty("Sweden")                             @JsonAlias({"SE","SWE"}) SWEDEN("Sweden","SE","SWE"),
    @JsonProperty("Switzerland")                        @JsonAlias({"CH","CHE"}) SWITZERLAND("Switzerland","CH","CHE"),
    @JsonProperty("Syria")                              @JsonAlias({"SY","SYR"}) SYRIA("Syria","SY","SYR"),
    @JsonProperty("Taiwan")                             @JsonAlias({"TW","TWN"}) TAIWAN("Taiwan","TW","TWN"),
    @JsonProperty("Tajikistan")                         @JsonAlias({"TJ","TJK"}) TAJIKISTAN("Tajikistan","TJ","TJK"),
    @JsonProperty("Tanzania")                           @JsonAlias({"TZ","TZA"}) TANZANIA("Tanzania","TZ","TZA"),
    @JsonProperty("Thailand")                           @JsonAlias({"TH","THA"}) THAILAND("Thailand","TH","THA"),
    @JsonProperty("Togo")                               @JsonAlias({"TG","TGO"}) TOGO("Togo","TG","TGO"),
    @JsonProperty("Tokelau")                            @JsonAlias({"TK","TKL"}) TOKELAU("Tokelau","TK","TKL"),
    @JsonProperty("Tonga")                              @JsonAlias({"TO","TON"}) TONGA("Tonga","TO","TON"),
    @JsonProperty("Trinidad and Tobago")                @JsonAlias({"TT","TTO"}) TRINIDAD_AND_TOBAGO("Trinidad and Tobago","TT","TTO"),
    @JsonProperty("Tunisia")                            @JsonAlias({"TN","TUN"}) TUNISIA("Tunisia","TN","TUN"),
    @JsonProperty("Turkey")                             @JsonAlias({"TR","TUR"}) TURKEY("Turkey","TR","TUR"),
    @JsonProperty("Turkmenistan")                       @JsonAlias({"TM","TKM"}) TURKMENISTAN("Turkmenistan","TM","TKM"),
    @JsonProperty("Turks and Caicos Islands")           @JsonAlias({"TC","TCA"}) TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands","TC","TCA"),
    @JsonProperty("Tuvalu")                             @JsonAlias({"TV","TUV"}) TUVALU("Tuvalu","TV","TUV"),
    @JsonProperty("U.S. Virgin Islands")                @JsonAlias({"VI","VIR"}) US_VIRGIN_ISLANDS("U.S. Virgin Islands","VI","VIR"),
    @JsonProperty("Uganda")                             @JsonAlias({"UG","UGA"}) UGANDA("Uganda","UG","UGA"),
    @JsonProperty("Ukraine")                            @JsonAlias({"UA","UKR"}) UKRAINE("Ukraine","UA","UKR"),
    @JsonProperty("United Arab Emirates")               @JsonAlias({"AE","ARE"}) UNITED_ARAB_EMIRATES("United Arab Emirates","AE","ARE"),
    @JsonProperty("United Kingdom")                     @JsonAlias({"GB","GBR"}) UNITED_KINGDOM("United Kingdom","GB","GBR"),
    @JsonProperty("United States")                      @JsonAlias({"US","USA"}) UNITED_STATES("United States","US","USA"),
    @JsonProperty("Uruguay")                            @JsonAlias({"UY","URY"}) URUGUAY("Uruguay","UY","URY"),
    @JsonProperty("Uzbekistan")                         @JsonAlias({"UZ","UZB"}) UZBEKISTAN("Uzbekistan","UZ","UZB"),
    @JsonProperty("Vanuatu")                            @JsonAlias({"VU","VUT"}) VANUATU("Vanuatu","VU","VUT"),
    @JsonProperty("Vatican")                            @JsonAlias({"VA","VAT"}) VATICAN("Vatican","VA","VAT"),
    @JsonProperty("Venezuela")                          @JsonAlias({"VE","VEN"}) VENEZUELA("Venezuela","VE","VEN"),
    @JsonProperty("Vietnam")                            @JsonAlias({"VN","VNM"}) VIETNAM("Vietnam","VN","VNM"),
    @JsonProperty("Wallis and Futuna")                  @JsonAlias({"WF","WLF"}) WALLIS_AND_FUTUNA("Wallis and Futuna","WF","WLF"),
    @JsonProperty("Western Sahara")                     @JsonAlias({"EH","ESH"}) WESTERN_SAHARA("Western Sahara","EH","ESH"),
    @JsonProperty("Yemen")                              @JsonAlias({"YE","YEM"}) YEMEN("Yemen","YE","YEM"),
    @JsonProperty("Zambia")                             @JsonAlias({"ZM","ZMB"}) ZAMBIA("Zambia","ZM","ZMB"),
    @JsonProperty("Zimbabwe")                           @JsonAlias({"ZW","ZWE"}) ZIMBABWE("Zimbabwe","ZW","ZWE")
    ;


    private final String englishName;
    private final String twoLetterCode;
    private final String threeLetterCode;


    Country(String englishName, String twoLetterCode, String threeLetterCode) {
        this.englishName = englishName;
        this.twoLetterCode = twoLetterCode;
        this.threeLetterCode = threeLetterCode;
    }

    public String getEnglishName() {
        return englishName;
    }

    public String getTwoLetterCode() {
        return twoLetterCode;
    }

    public String getThreeLetterCode() {
        return threeLetterCode;
    }
}
